CREATE OR REPLACE FUNCTION spCreateExternalUniqueID(
  _InputUniqueID UNIQUEIDENTIFIER = NULL
)
RETURNS UNIQUEIDENTIFIER
AS $$
DECLARE
  _ExternalUniqueID UNIQUEIDENTIFIER := _InputUniqueID;
BEGIN
  IF _ExternalUniqueID IS NULL AND CONTEXT_INFO() IS NULL THEN
    SET _ExternalUniqueID = NEWID();
  ELSEIF _ExternalUniqueID IS NOT NULL THEN
    SET CONTEXT_INFO(_ExternalUniqueID);
  ELSEIF CONTEXT_INFO() IS NOT NULL THEN
    SET _ExternalUniqueID = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
  END IF;

  RETURN _ExternalUniqueID;
END;
$$ LANGUAGE plpgsql;